### ISSUE TITLE
get a variable value

### ISSUE THREAD

**Issue by durielz** [Brewskey/spark-server#54] opened 2017-01-01 18:16 UTC
Hi again, when i try to get a var value by requesting /v1/devices/:deviceID/:varName/ the response is:

`{
  "result": "[object Object]"
}`

**Comment by AntonPuko** [comment] 2017-01-01 18:51
Hi, could you see in debugger or console.log what [object Object] actually is? I can't reproduce. I get { result: varValue } at least for INT.

**Comment by durielz** [comment] 2017-01-01 18:59
if i console.log the varValue i get [object Object] again. With the old spark-server i get:
`{
  "cmd": "VarReturn",
  "name": "config",
  "result": "{ \"t_threshold\": \"24\", \"flow_threshold\": \"50\" }",
  "coreInfo": {
    "connected": true
  }
}`

**Comment by durielz** [comment] 2017-01-02 12:52
Your code seems to work in the same way as the old one, so i don't understand why but if i change the line 318 in lib/Messages.js in protocol
`return newBuffer.toString();`
to 
`return buffer.toString();`
so without process data with BufferReader, it works.

hope it can help you

**Comment by AntonPuko** [comment] 2017-01-02 14:13
Thanks, @durielz. with `return newBuffer.toString();` - fromBinary() returns stringified bufferReader object, instead of actual string from buffer ^.^, so you see '[object object]'. In the old code, there were like you do: return buffer.toString();...so nice catch.
will be fixed in that PR:  https://github.com/Brewskey/spark-protocol/pull/14

**Closed** 2017-01-03 17:42 UTC

**Comment by wdimmit** [comment] 2017-01-03 19:52
Using spark-protocol (commit ecd803d), I'm still seeing the `{ "result": "[object Object]" }` whenever I try to pull a string result from a variable.  Int values come through normally.

**Comment by AntonPuko** [comment] 2017-01-03 21:33
hm. just checked. works ok with strings for me.
could you check. what do you have as bufferReader.buffer, when do calls, here: 
https://github.com/Brewskey/spark-protocol/blob/master/src/lib/Messages.js#L312

**Comment by wdimmit** [comment] 2017-01-03 21:36
Line 312 is:  `return bufferReader.buffer.toString();`
